In [1]:
#Numpy - Array Manipulation.

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10 , (3,4))

In [4]:
arr

array([[3, 2, 1, 1],
       [6, 8, 6, 5],
       [1, 3, 8, 9]], dtype=int32)

In [5]:
arr.reshape(6,2)

array([[3, 2],
       [1, 1],
       [6, 8],
       [6, 5],
       [1, 3],
       [8, 9]], dtype=int32)

In [6]:
arr.reshape(2,6)

array([[3, 2, 1, 1, 6, 8],
       [6, 5, 1, 3, 8, 9]], dtype=int32)

In [7]:
arr.reshape(2,-242342)

array([[3, 2, 1, 1, 6, 8],
       [6, 5, 1, 3, 8, 9]], dtype=int32)

In [8]:
arr.T

array([[3, 6, 1],
       [2, 8, 3],
       [1, 6, 8],
       [1, 5, 9]], dtype=int32)

In [9]:
arr

array([[3, 2, 1, 1],
       [6, 8, 6, 5],
       [1, 3, 8, 9]], dtype=int32)

In [10]:
arr.flatten()

array([3, 2, 1, 1, 6, 8, 6, 5, 1, 3, 8, 9], dtype=int32)

In [11]:
arr1 = np.array([1,2,3,3,4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1 ,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1 ,axis=0)

array([[1, 2, 3, 3, 4]])

In [15]:
arr

array([[3, 2, 1, 1],
       [6, 8, 6, 5],
       [1, 3, 8, 9]], dtype=int32)

In [16]:
np.squeeze(arr)

array([[3, 2, 1, 1],
       [6, 8, 6, 5],
       [1, 3, 8, 9]], dtype=int32)

In [17]:
data = np.array([[1] , [2] , [3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 3, 4])

In [21]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [22]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [23]:
arr1

array([1, 2, 3, 3, 4])

In [24]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [25]:
# Numpy - Binary Operators.

In [26]:
arr1 = np.random.randint(1,10 , (3,4))

In [27]:
arr2 = np.random.randint(1,10 , (3,4))

In [28]:
arr1

array([[1, 3, 9, 6],
       [7, 6, 6, 6],
       [6, 1, 6, 7]], dtype=int32)

In [29]:
arr2

array([[8, 2, 1, 6],
       [2, 9, 9, 4],
       [8, 6, 2, 1]], dtype=int32)

In [30]:
arr1+arr2

array([[ 9,  5, 10, 12],
       [ 9, 15, 15, 10],
       [14,  7,  8,  8]], dtype=int32)

In [31]:
arr1*arr2

array([[ 8,  6,  9, 36],
       [14, 54, 54, 24],
       [48,  6, 12,  7]], dtype=int32)

In [32]:
arr1/arr2

array([[0.125     , 1.5       , 9.        , 1.        ],
       [3.5       , 0.66666667, 0.66666667, 1.5       ],
       [0.75      , 0.16666667, 3.        , 7.        ]])

In [33]:
arr1-arr2

array([[-7,  1,  8,  0],
       [ 5, -3, -3,  2],
       [-2, -5,  4,  6]], dtype=int32)

In [34]:
arr1%arr2

array([[1, 1, 0, 0],
       [1, 6, 6, 2],
       [6, 1, 0, 0]], dtype=int32)

In [35]:
arr1 ** arr2

array([[       1,        9,        9,    46656],
       [      49, 10077696, 10077696,     1296],
       [ 1679616,        1,       36,        7]], dtype=int32)

In [36]:
arr1 & arr2

array([[0, 2, 1, 6],
       [2, 0, 0, 4],
       [0, 0, 2, 1]], dtype=int32)

In [37]:
arr1

array([[1, 3, 9, 6],
       [7, 6, 6, 6],
       [6, 1, 6, 7]], dtype=int32)

In [38]:
arr2

array([[8, 2, 1, 6],
       [2, 9, 9, 4],
       [8, 6, 2, 1]], dtype=int32)

In [39]:
~arr1

array([[ -2,  -4, -10,  -7],
       [ -8,  -7,  -7,  -7],
       [ -7,  -2,  -7,  -8]], dtype=int32)

In [40]:
arr1|arr2

array([[ 9,  3,  9,  6],
       [ 7, 15, 15,  6],
       [14,  7,  6,  7]], dtype=int32)

In [41]:
arr1>arr2

array([[False,  True,  True, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [42]:
#Numpy - String Functions.

In [43]:
arr = np.array(['sudh' , "Kumar"])

In [44]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [45]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [46]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [47]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [48]:
# Numpy - Mathematical Functions.

In [49]:
arr1

array([[1, 3, 9, 6],
       [7, 6, 6, 6],
       [6, 1, 6, 7]], dtype=int32)

In [50]:
np.sin(arr1)

array([[ 0.84147098,  0.14112001,  0.41211849, -0.2794155 ],
       [ 0.6569866 , -0.2794155 , -0.2794155 , -0.2794155 ],
       [-0.2794155 ,  0.84147098, -0.2794155 ,  0.6569866 ]])

In [51]:
np.cos(arr1)

array([[ 0.54030231, -0.9899925 , -0.91113026,  0.96017029],
       [ 0.75390225,  0.96017029,  0.96017029,  0.96017029],
       [ 0.96017029,  0.54030231,  0.96017029,  0.75390225]])

In [52]:
np.tan(arr1)

array([[ 1.55740772, -0.14254654, -0.45231566, -0.29100619],
       [ 0.87144798, -0.29100619, -0.29100619, -0.29100619],
       [-0.29100619,  1.55740772, -0.29100619,  0.87144798]])

In [53]:
np.tanh(arr1)

array([[0.76159416, 0.99505475, 0.99999997, 0.99998771],
       [0.99999834, 0.99998771, 0.99998771, 0.99998771],
       [0.99998771, 0.76159416, 0.99998771, 0.99999834]])

In [54]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.95424251, 0.77815125],
       [0.84509804, 0.77815125, 0.77815125, 0.77815125],
       [0.77815125, 0.        , 0.77815125, 0.84509804]])

In [55]:
np.exp(arr1)

array([[2.71828183e+00, 2.00855369e+01, 8.10308393e+03, 4.03428793e+02],
       [1.09663316e+03, 4.03428793e+02, 4.03428793e+02, 4.03428793e+02],
       [4.03428793e+02, 2.71828183e+00, 4.03428793e+02, 1.09663316e+03]])

In [56]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 3.        , 2.44948974],
       [2.64575131, 2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 1.        , 2.44948974, 2.64575131]])

In [57]:
np.power(arr1,2)

array([[ 1,  9, 81, 36],
       [49, 36, 36, 36],
       [36,  1, 36, 49]], dtype=int32)

In [58]:
np.mean(arr1)

np.float64(5.333333333333333)

In [59]:
np.median(arr1)

np.float64(6.0)

In [60]:
np.std(arr1)

np.float64(2.321398046197353)

In [61]:
np.var(arr1)

np.float64(5.388888888888888)

In [62]:
np.min(arr1)

np.int32(1)

In [63]:
np.max(arr1)

np.int32(9)