In [368]:
import numpy as np

In [369]:
l = [1,2,3,4]

In [370]:
ar = np.array(l)

In [371]:
ar

array([1, 2, 3, 4])

In [372]:
type(ar)

numpy.ndarray

In [373]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [374]:
np.asarray(l)

array([1, 2, 3, 4])

In [375]:
a= [2,3,4]

In [376]:
np.asanyarray(a)

array([2, 3, 4])

In [377]:
b = np.matrix(l)

In [378]:
b

matrix([[1, 2, 3, 4]])

In [379]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [380]:
a = np.array(l)

In [381]:
a


array([1, 2, 3, 4])

In [382]:
# shallow copy
c = a  

In [383]:
c

array([1, 2, 3, 4])

In [384]:
a

array([1, 2, 3, 4])

In [385]:
c[0] = 100

In [386]:
c

array([100,   2,   3,   4])

In [387]:
a

array([100,   2,   3,   4])

In [388]:
# deep copy
d = np.copy(a)

In [389]:
d

array([100,   2,   3,   4])

In [390]:
a

array([100,   2,   3,   4])

In [391]:
a[1] = 400

In [392]:
a

array([100, 400,   3,   4])

In [393]:
d

array([100,   2,   3,   4])

In [394]:
np.fromfunction(lambda i, j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [395]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [396]:
iterable = (i*i for i in range(5))

In [397]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [398]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [399]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

In [400]:
#Numpy - Data Types.

In [401]:
l = [2,3,4,5,6]

In [402]:
ar = np.array(l)

In [403]:
ar

array([2, 3, 4, 5, 6])

In [404]:
ar.ndim

1

In [405]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [406]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [407]:
ar2.ndim

2

In [408]:
ar.size

5

In [409]:
ar2.size

8

In [410]:
ar

array([2, 3, 4, 5, 6])

In [411]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [412]:
ar.shape

(5,)

In [413]:
ar2.shape

(2, 4)

In [414]:
ar.dtype

dtype('int64')

In [415]:
ar2.dtype


dtype('int64')

In [416]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [417]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [418]:
ar22.dtype

dtype('float64')

In [419]:
list(range(5))

[0, 1, 2, 3, 4]

In [420]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [63]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [65]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [112]:
ar4 = np.zeros((3,4,2,3))

In [114]:
ar4.ndim


4

In [73]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
on =np.ones((2,3,2))

In [57]:
on + 5


array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [4]:
on *4


NameError: name 'on' is not defined

In [219]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [220]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [62]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [222]:
arr = np.random.randn(3,4)

In [223]:
arr

array([[ 0.02022771,  0.04557534,  0.20909306, -0.03982665],
       [ 0.32116559, -0.02867694, -0.11644587,  0.12169271],
       [-0.34817654, -0.34489423, -1.42212152,  1.12837025]])

In [237]:
import pandas as pd 

In [238]:
pd.DataFrame(arr)

0         1         2         3
0  0.523439  0.959825  0.465625  0.530199
1  0.902563  0.689487  0.981573  0.898253
2  0.234122  0.058002  0.206483  0.556551

In [239]:
np.random.rand(3,4)

array([[0.90988031, 0.64576085, 0.1115675 , 0.74637656],
       [0.29043192, 0.99778466, 0.85289505, 0.11042707],
       [0.31623516, 0.12855106, 0.0610391 , 0.98181871]])

In [240]:
np.random.randint(1,110 , (3,4))

array([[ 16,  65,  98, 101],
       [ 43,  92,  58,  33],
       [104,  53, 105,  65]], dtype=int32)

In [ ]:
pd.DataFrame(np.random.randint(1,110 , (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     43  107   18   79   48   16   83   20   23   94  ...   39   65   72   
1     48   93   34   42   33    8   79   98   25   36  ...   34   79   43   
2     67   42   77   80   85   96   39  106   94   36  ...  108   43   59   
3     40   31    7  108   40   86   37   41    7  108  ...   48   58   69   
4     15   46   95   98  106   75   97   58   44   94  ...   11  105   55   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   76   99   70   80   61    3   77  103  106   85  ...   83   42   22   
296   51   68   39   96   67   63   41   73   35   76  ...   71   24   55   
297  100   64   78   45   73   20  105   85   77   30  ...    5   99   15   
298   68   99   26    4   32   85   59   43   86   16  ...   23   34   42   
299   64   60   14   71   15   81   26   92   17   39  ...   15   10   71   

     393  394  395  396  397  398  399  
0     11    1   29   69   42   29   29  
1     35   53   69   29   55   64   56  
2      1   62   73  109   95   97   11  
3      4   84   89   35   87  106   57  
4     69   77   15   71   34   44   57  
..   ...  ...  ...  ...  ...  ...  ...  
295   37   40   13   50  100   74  103  
296   95   31  109   82   11   71  109  
297   64   10   36   41    7   98   32  
298   32   56   62   88   83   16   59  
299   47   65   94   50   80   46   26  

[300 rows x 400 columns]

In [242]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')

In [243]:
arr = np.random.rand(3,4)

In [244]:
arr

array([[0.69263701, 0.66246303, 0.53744454, 0.26857821],
       [0.92622509, 0.3381813 , 0.68776456, 0.6370894 ],
       [0.64441556, 0.00733947, 0.58373032, 0.67374131]])

In [245]:
arr.reshape(6,-1)

array([[0.69263701, 0.66246303],
       [0.53744454, 0.26857821],
       [0.92622509, 0.3381813 ],
       [0.68776456, 0.6370894 ],
       [0.64441556, 0.00733947],
       [0.58373032, 0.67374131]])

In [246]:
arr1 = arr.reshape(6,-134353553435)

In [247]:
arr1

array([[0.69263701, 0.66246303],
       [0.53744454, 0.26857821],
       [0.92622509, 0.3381813 ],
       [0.68776456, 0.6370894 ],
       [0.64441556, 0.00733947],
       [0.58373032, 0.67374131]])

In [248]:
arr1[1][1]

np.float64(0.2685782120071377)

In [249]:
arr1[2:5]

array([[0.92622509, 0.3381813 ],
       [0.68776456, 0.6370894 ],
       [0.64441556, 0.00733947]])

In [74]:
arr1[2:5,1]

array([0.11261271, 0.88517468, 0.95834463])

In [75]:
arr = np.random.randint(1,100 , (5,5))

In [76]:
arr

array([[80, 92, 12, 85, 96],
       [64, 26,  4, 97, 81],
       [ 3, 48, 90, 71,  7],
       [16, 94, 66, 73, 18],
       [ 9, 87, 75, 60, 52]], dtype=int32)

In [77]:
arr[arr>50]

array([80, 92, 85, 96, 64, 97, 81, 90, 71, 94, 66, 73, 87, 75, 60, 52],
      dtype=int32)

In [78]:
arr

array([[80, 92, 12, 85, 96],
       [64, 26,  4, 97, 81],
       [ 3, 48, 90, 71,  7],
       [16, 94, 66, 73, 18],
       [ 9, 87, 75, 60, 52]], dtype=int32)

In [79]:
arr[2:4 , [1,2]]

array([[48, 90],
       [94, 66]], dtype=int32)

In [80]:
arr[0][0] = 5000

In [81]:
arr

array([[5000,   92,   12,   85,   96],
       [  64,   26,    4,   97,   81],
       [   3,   48,   90,   71,    7],
       [  16,   94,   66,   73,   18],
       [   9,   87,   75,   60,   52]], dtype=int32)

In [356]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [357]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [358]:
arr2


array([[2, 2, 2],
       [1, 2, 1],
       [2, 1, 2]], dtype=int32)

In [359]:
arr1+arr2

array([[3, 4, 3],
       [3, 3, 3],
       [4, 2, 4]], dtype=int32)

In [360]:
arr1-arr2

array([[-1,  0, -1],
       [ 1, -1,  1],
       [ 0,  0,  0]], dtype=int32)

In [87]:
arr1/arr2

array([[1. , 1. , 2. ],
       [1. , 0.5, 1. ],
       [2. , 1. , 1. ]])

In [361]:
arr1 * arr2

array([[2, 4, 2],
       [2, 2, 2],
       [4, 1, 4]], dtype=int32)

In [362]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 2]], dtype=int32)

In [363]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [2, 1, 2]], dtype=int32)

In [364]:
arr1@arr2

array([[6, 7, 6],
       [9, 8, 9],
       [9, 8, 9]], dtype=int32)

In [365]:
arr1/0

C:\Users\singh\AppData\Local\Temp\ipykernel_3188\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [93]:
arr1 +100

array([[101, 101, 102],
       [101, 101, 102],
       [102, 101, 101]], dtype=int32)

In [94]:
arr1**2

array([[1, 1, 4],
       [1, 1, 4],
       [4, 1, 1]], dtype=int32)

In [95]:
#Numpy – Broadcasting.

In [96]:
arr =np.zeros((4,4))

In [97]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
row = np.array([1,2,3,4])

In [99]:
row.shape

(4,)

In [100]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [101]:
row.T

array([1, 2, 3, 4])

In [422]:
col = np.array([[1,2,3,4]])

In [423]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [103]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [104]:
col

array([[1, 2, 3, 4]])

In [105]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
arr1 = np.random.randint(1,4 , (3,4))

In [107]:
arr1

array([[1, 2, 1, 2],
       [3, 2, 2, 2],
       [2, 1, 3, 3]], dtype=int32)

In [108]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        , 1.41421356],
       [1.73205081, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.73205081, 1.73205081]])

In [109]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 ,  2.71828183,  7.3890561 ],
       [20.08553692,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  2.71828183, 20.08553692, 20.08553692]])

In [110]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.        , 0.30103   ],
       [0.47712125, 0.30103   , 0.30103   , 0.30103   ],
       [0.30103   , 0.        , 0.47712125, 0.47712125]])